### ISSUE TITLE
Draft a UG for v1.2

### ISSUE THREAD

**Issue by jieffyy** [AY2021S1-CS2103T-T11-2/tp#2]
Things that need updating:

- [x] Creating @athuyaoo 
- [x] Reading @schoolex 
- [x] Editing @teekoksiang 
- [x] Deleting @lowjiefeng1998 
- [x] Exporting @yanchenglee98 

Then, consolidate and upload to LumiNUS.

**Comment by yanchenglee98** [comment]
Completed, closing issue
