### ISSUE TITLE
Unclear error message when adding resident with duplicate matriculation number

### ISSUE THREAD

**Issue by yanchenglee98** [AY2021S1-CS2103T-T11-2/tp#285]
Steps to replicate it:
1) Delete addressbook.json and use the default residents list
2) Add a resident with the matriculation number that is already used e.g. A0123456B

Error message used to be clearer stating that matriculation number is a duplicate.
Same applies for Room number

![image](https://user-images.githubusercontent.com/59784190/98466049-0aba5b00-2208-11eb-96bd-2bd9c290157c.png)

**Comment by athuyaoo** [comment]
Closed by #287
