### ISSUE TITLE
Commands to edit blocks, levels and rooms ranges 

### ISSUE THREAD

**Issue by jieffyy** [AY2021S1-CS2103T-T11-2/tp#69]
As stated.

Add commands for users to edit blocks and rooms ranges via the CLI. \
Ensure that the user cannot delete a block/room when there is one or more resident current staying there.

The data should be persisted in the `data/addressbook.json` file.

When advanced users update the `data/addressbook.json` file, and they mess up, all their data will be removed (still present in the log files though).

**Comment by teekoksiang** [comment]
Close as it is open in #180
