### ISSUE TITLE
Bug in the add command

### ISSUE THREAD

**Issue by jieffyy** [AY2021S1-CS2103T-T11-2/tp#81]
Please see below. Seems like there are some fields missing in the GUI's error message.

![image](https://user-images.githubusercontent.com/19956058/95822005-a964b080-0d5d-11eb-8d11-bcb43cd720a9.png)

**Comment by schoolex** [comment]
Will fix this bug

**Comment by jieffyy** [comment]
Nice, thanks! 😄
